---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: timezone
    command: /sbin/init
    image: ${MOLECULE_IMAGE}
    privileged: True
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
      roles_path: "$HOME/.ansible/roles/:/tmp"
  connection_options:
    system_timezone: Asia/Tokyo
verifier:
  name: ansible
scenario:
  test_sequence:
    - syntax
    - create
    - converge
    - idempotence
    - verify
